name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test

      - name: npm run export
        run: npm run export
